### ISSUE TITLE
Bitbucket pipelines CI

### ISSUE THREAD

**Issue by matjack1** [datocms/product-roadmap#120]
Would be useful to have a build integration with Bitbucket pipelines CI.

A pipeline can be triggered via this API: https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/pipelines/#post

**Comment by trickydisco78** [comment]
yea looks like it needs oauth credentials and an object payload with the api call

**Comment by matjack1** [comment]
We are sorry but we are not going to implement this integration in any foreseeable future as we had very few requests and we need to minimise the code needed to integrate with third parties.

If we start hearing more requests here we might reconsider our choice.
