### ISSUE TITLE
Be able to abort a deployment without admin access

### ISSUE THREAD

**Issue by Angelmmiguel** [datocms/product-roadmap#129]
**Is your feature request related to a problem? Please describe.**

We've an internal system to deploy our site. When an editor clicks on the "Build Now" button inside the "STATUS" dropdown, it triggers a new build on our side. However, sometimes this process fails very early and it cannot notify the DatoCMS API, so the Deployment keeps running and editors cannot trigger a new deployment again.

Then, they need to notify us so we can enter the admin panel to click "Abort and Mark as failed". 

**Describe the solution you'd like**

I expect that after certain time, maybe based on the mean of older deployments, a new button link appears in the "STATUS" dropdown. This button will allow editors to abort a deployment and mark it as failed. For example:

![screenshot 2019-01-17 at 08 07 17](https://user-images.githubusercontent.com/4056725/51301297-00c1d980-1a2f-11e9-8e43-3f912ad9faab.png)

The feature will be exactly the same of the link inside the admin panel.

**Describe alternatives you've considered**

I think the solution above is the easiest way to do it.

**Additional context**

Not really. Ping me if you've more questions :)

**Comment by matjack1** [comment]
hey @Angelmmiguel this is now live! :)

**Comment by Angelmmiguel** [comment]
Oh! Thank you very much :D
