### ISSUE TITLE
Strip inline style from multiple-paragraph text field

### ISSUE THREAD

**Issue by matjack1** [datocms/product-roadmap#130]
**Is your feature request related to a problem? Please describe.**
When an editor paste content from Word (or similar) a lot of inline styles are saved in a field, possibly breaking the frontend.

**Describe the solution you'd like**
Strip all inline styles when saving content, if a preference is chosen in a multiple-paragraph text field

**Comment by stefanoverna** [comment]
Duplicate of #146
