### ISSUE TITLE
YAML Configuration of Content Types

### ISSUE THREAD

**Issue by d-cs** [datocms/product-roadmap#135]
**Is your feature request related to a problem? Please describe.**
I'm comfortable describing content types using structured data formats like JSON and YAML. It would be useful to be able to generate content types directly from a format like this. I appreciate there is the ability to duplicate content types, however adding fields can sometimes be quite repetitive. 

**Describe the solution you'd like**
When creating a new content type, an additional tab that says 'YAML', then I could copy/paste/tweak scripts this way.

**Describe alternatives you've considered**
At present I'm using the duplicate content type feature.

**Additional context**
I think the biggest use case would be that I could have field defaults such as all fields required, using copy paste rather than having to use the UI each time.

**Comment by d-cs** [comment]
This is potentially a duplicate of https://github.com/datocms/product-roadmap/issues/12?

**Comment by stefanoverna** [comment]
Yep! Closing this one!
