### ISSUE TITLE
Location input doesn't render nicely on small viewports

### ISSUE THREAD

**Issue by d-cs** [datocms/product-roadmap#137]
**Describe the bug**
Location field input gets stuck under the default Google Maps controls on smaller screen sizes.

**To Reproduce**
1. Create a collection with a location field
2. Set viewport width to 820px
3. Go to 'Content'
4. Adjust side menu bar to 215px wide
5. Location looks like screenshot

**Expected behavior**
I should still be able to at least see that the location search box has focus.

**Screenshots**
![screenshot 2019-01-28 at 11 22 37](https://user-images.githubusercontent.com/45313566/51833629-e4a41f00-22ef-11e9-9f3b-074a471f58b2.png)

**Additional context**
Depends on implementation, but if your using a react component to generate the map this may help: https://github.com/tomchentw/react-google-maps/issues/516

**Comment by stefanoverna** [comment]
Thanks for reporting @d-cs, this has been just fixed!
