### ISSUE TITLE
Display editor languages in order specified in settings

### ISSUE THREAD

**Issue by Convincible** [datocms/product-roadmap#138]
In my site settings, I specified the languages:

1. English
2. Arabic

However, in my editor, if both languages are present, it will display them in alphabetical order:

![image](https://user-images.githubusercontent.com/30758921/52176176-de59eb00-27a6-11e9-8a66-b8e9ee267d58.png)

This means that the record will always open to Arabic and require an extra click to English.

I specified them in a particular order to reflect the language's importance to the site. Most of the time it is an English site and editing is in English. Only occasionally we need a page translated to Arabic.

Please switch to always display the editor languages in the order the languages were specified.

Thanks!

**Comment by mzampetti** [comment]
Same pain in the a.. here. 100x upvotes for this feature!

![Screenshot 2019-05-13 at 10 27 02](https://user-images.githubusercontent.com/1792077/57606774-ef668500-7569-11e9-88ae-1a696618058e.png)

**Comment by stefanoverna** [comment]
Done!
