### ISSUE TITLE
Give options with previously created fields when adding a new field to model

### ISSUE THREAD

**Issue by souljuse** [datocms/product-roadmap#139]
When adding a field to a model it would be nice to have a select, similar to the one used to add new modular blocks in the content area, that allows to add a field already that is already used in the project. 

For example, I use a title for every model and it would be much faster if I could add it straight away without having to give the name title, key, localization etc, since it has always the same structure in every model. 

Ah! And if you edit one field, the modifications should apply to all other models

**Comment by stefanoverna** [comment]
Indefinitely postponed as it would make the UX more complex.
