### ISSUE TITLE
Ability to sort links

### ISSUE THREAD

**Issue by hesedel** [datocms/product-roadmap#140]
I'd like to be able to drag and move around links:

<img width="799" alt="screenshot 2019-02-12 at 11 48 47" src="https://user-images.githubusercontent.com/1061404/52630324-3afe8980-2ebc-11e9-9bbc-e1560e1a3dfc.png">

**Comment by stefanoverna** [comment]
It's already possible @hesedel! 

![2019-02-25 17 24 21](https://user-images.githubusercontent.com/51573/53351961-4329e080-3922-11e9-9c6d-df2cde69141d.gif)
