### ISSUE TITLE
Content editing tabs

### ISSUE THREAD

**Issue by flipxfx** [datocms/product-roadmap#143]
**Is your feature request related to a problem? Please describe.**
We have some models that have multiple html fields or a lot of fields. These can make the model edit quite long.

**Describe the solution you'd like**
We would like the ability to group some fields in other tabs to make editing easier. For example, we might have an html field for an office location to describe the general office, but we also want an html field that describes the office emergency preparedness, office guidelines etc. It would be nice to have tabs that will hold those fields for an office location.

Would also be nice just to group certain fields, like metadata, in a separate tab.

**Describe alternatives you've considered**
Just having a super long model editing.

**Comment by stefanoverna** [comment]
Related to https://github.com/datocms/product-roadmap/issues/13
