### ISSUE TITLE
add a list of IDs to _all[Model]sMeta

### ISSUE THREAD

**Issue by lunelson** [datocms/product-roadmap#144]
I've run in to a blocker, trying to get a filtered, paginated list of items in a randomized order. 

If the `_all[Model]sMeta` would return an array of IDs in addition to the `count` parameter, there would be more possibilities: for example I could shuffle and paginate that list of IDs manually then use it in a second query's filter, simply matching against ID.

Although I can understand the pagination limit of 100 for regular queries, a simple list of matched IDs on the meta query would be quite low-bandwidth. I hope you'll consider implementing it.

**Comment by stefanoverna** [comment]
It's not an easy task for multiple reasons.. we won't work on this in the foreseeable future, sorry :( I might suggest creating a field with a plugin that generates random values to records?
