### ISSUE TITLE
Fast edit links for model and fields in Content view

### ISSUE THREAD

**Issue by mzampetti** [datocms/product-roadmap#152]
Is slow to switch from Content and Admin, find the Model, edit stuff. Go back. Find new stuff to edit. Start again.
A button to edit the model and fields from Content would be fantastic.

![Screenshot 2019-04-05 at 11 01 23](https://user-images.githubusercontent.com/1792077/55616834-0360df00-5793-11e9-97b1-dac5f0a7643b.png)

![Screenshot 2019-04-05 at 11 04 43](https://user-images.githubusercontent.com/1792077/55616845-0b208380-5793-11e9-89db-7a65101f1f4d.png)

**Comment by stefanoverna** [comment]
Done! 

<img width="1295" alt="Screenshot 2019-04-19 00 13 01" src="https://user-images.githubusercontent.com/51573/56394555-026e8980-6238-11e9-89dd-75ee5f6ea721.png">

**Comment by stefanoverna** [comment]
![2019-04-19 00 14 29](https://user-images.githubusercontent.com/51573/56394612-2f22a100-6238-11e9-9cda-f7193f8bf15f.gif)
