### ISSUE TITLE
SEO Block z-index and modular content dropdown

### ISSUE THREAD

**Issue by panoply** [datocms/product-roadmap#153]
**Description**
There is a z-index issue on the SEO block when you have a multiple modular component dropdown. The issue occurs on initial load. If you interact with SEO block the dropdown will behave as expected.   

![zindex-error](https://user-images.githubusercontent.com/7041324/56445932-0239c100-6300-11e9-88ef-c4554f7bd3f1.gif)

**Comment by stefanoverna** [comment]
Should be fixed now, thanks for the report @panoply!
