### ISSUE TITLE
Querying more than the GraphQL API request limit should error out

### ISSUE THREAD

**Issue by lunelson** [datocms/product-roadmap#158]
**Describe the bug**
Querying any collection of records via graphQL silently fails to return more than 100 results.

**To Reproduce**
```graphql
{
  allPosts(first: 1000) {
    id
  }
}
```
**Expected behavior**
Querying for more than the limit amount (currently 100) should error out. A silent failure is a bummer.

**Comment by matjack1** [comment]
Thank you for reporting this. You are right that we should notify the user about the limit, I'll add this to our development backlog.

**Comment by sebbean** [comment]
*ahem* charge more *ahem*

**Comment by stefanoverna** [comment]
Fixed!
