### ISSUE TITLE
Filtering single-links by`in` returns no records when given empty array

### ISSUE THREAD

**Issue by lunelson** [datocms/product-roadmap#159]
**Describe the bug**
Filtering records by single-links with `in`, given an empty array should return all the records, like filtering multiple-link connections with `anyIn` when given empty array.

**To Reproduce**
The following query will return the first 100 `Post` records, because it is the equivalent of an inactive filter:
```graphql
{
  items: allPosts(first: 100, filter: {series: {anyIn: []}}) {
    id
  }
}
```
This query will return 0 `Post` records.
```graphql
{
  items: allPosts(first: 100, filter: {author: {in: []}}) {
    id
  }
}
```

**Expected behavior**
Filtering records by single-link references using `in`, given an empty array of ids, should just return all of the former records, in order to be logically consistent.

**Comment by matjack1** [comment]
Thank you @lunelson I think you are right. I've added this to our development backlog.

**Comment by stefanoverna** [comment]
Fixed!
