### ISSUE TITLE
Modular fields with requirement of one disabled add another button

### ISSUE THREAD

**Issue by wildpow** [datocms/product-roadmap#161]
**Is your feature request related to a problem? Please describe.**
A modular field with a requirement of one still allows an editor to add an another. Editor calls me to help them figure out why they can't save the content if they miss the small visual indication (red text).

**Describe the solution you'd like**
The add button should be disabled or hidden after first content is added to avoid confusion.

**Describe alternatives you've considered**
Maybe having a better visual indication of the editor's error like bolder or underlined text. 

**Additional context**
![after adding first piece of content](https://user-images.githubusercontent.com/17464319/58664365-59f61f80-82e3-11e9-9b27-4c343e670057.png)

![Adding another piece of content](https://user-images.githubusercontent.com/17464319/58664412-6da18600-82e3-11e9-8b67-2b718080685e.png)

**Comment by stefanoverna** [comment]
Done! :) Thanks for the feedback @wildpow !
