### ISSUE TITLE
Support uploading media from rich text editor's image button

### ISSUE THREAD

**Issue by lunchbag** [datocms/product-roadmap#164]
**Is your feature request related to a problem? Please describe.**
When I'm trying to add a new blog post and there are images to include, it feels disjointed to have to save my progress, go to Media, upload an image, and then go back to my blog post to pick the image I just uploaded.

**Describe the solution you'd like**
I would love to be able to upload Media from the rich text editor so I can stay on one page.

**Describe alternatives you've considered**
Not much other than uploading all my images in the beginning or just going back and forth.

**Comment by stefanoverna** [comment]
Not EXACTLY the same thing, but you can already upload an image without interruptions :)

![2019-06-07 07 25 13](https://user-images.githubusercontent.com/51573/59082961-a221cd00-88f5-11e9-87b8-7e6484206d8a.gif)

**Comment by lunchbag** [comment]
@stefanoverna Great, thanks!
