### ISSUE TITLE
Trigger events for webhooks with payload 

### ISSUE THREAD

**Issue by bl4val** [datocms/product-roadmap#168]
**Is your feature request related to a problem? Please describe.**
We want to trigger different bitbucket pipelines depending on which models / records have changed.

**Describe the solution you'd like**
In dato webhooks you can specify trigger events, but not payload.
In dato development environments you can specify payload but not event triggers.
A good solution would be to add payload to webhooks or event triggers to development environments.

**Describe alternatives you've considered**
One alternative would be to use webhooks to a custom built application that translates the request to a request that bitbucket accepts.

**Comment by stefanoverna** [comment]
That's a good idea :+1:

**Comment by stefanoverna** [comment]
Done! https://www.datocms.com/changelog/customize-webhooks-http-body-with-mustache-templates
