### ISSUE TITLE
Enable SAML-based SSO for users of the platform

### ISSUE THREAD

**Issue by jim-hashicorp** [datocms/product-roadmap#169]
**Is your feature request related to a problem? Please describe.**
As our company grows, it's nice to be able to automatically provide access to platforms whenever possible.  While the Admin UI of DatoCMS is very easy to use, being able to JIT-provision users would be great to have (as well as de-provisioning if someone leaves)!

**Describe the solution you'd like**
SAML connectors to platforms like Okta, OneLogin, etc.

**Describe alternatives you've considered**
Google Auth would also be great, as our users already have MFA there!  

**Additional context**
Happy to help test and work on SAML connectors with the team!

**Comment by matjack1** [comment]
hey @jim-hashicorp we can add SAML-based SSO integration in enterprise plans, but we need to do some custom work.

If you are interested in discussing this further please let us know over support@datocms.com

Thanks!
