### ISSUE TITLE
False-positive singular name for Module Block

### ISSUE THREAD

**Issue by hellojebus** [datocms/product-roadmap#170]
**Describe the bug**
The validation engine that determines whether a modular content title is in singular form, is prone to false-positives.

**Expected behavior**
Normally, if it ends with (s) it can trigger this, but in this case this is the singular name of CTA (Don't want to type Call To Action, as I will have different types of CTA's)

**Screenshots**
<img width="649" alt="Screen Shot 2019-07-10 at 9 12 33 PM" src="https://user-images.githubusercontent.com/594042/61021759-b7a46f80-a357-11e9-9c10-a2ff6547261f.png">

**Comment by matjack1** [comment]
@hellojebus yes, unfortunately we cannot fix this issue entirely as we should add too many special cases.

What we can recommend in these instances is to append `_field`, `_model` or whatever you find useful at the end of the name to avoid any problem.
