### ISSUE TITLE
"Select Dropdown/Option" Modular Content

### ISSUE THREAD

**Issue by hellojebus** [datocms/product-roadmap#171]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
An "options" modular content field that could be either a select/radio option, where all option labels/values can be customized.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by stefanoverna** [comment]
Duplicate of #41

**Comment by stefanoverna** [comment]
We also have plugins to do that! https://www.datocms.com/plugins/i/@stackbitdatocms-plugin-typed-list
