### ISSUE TITLE
Bug: Defining default value color on existing record fails

### ISSUE THREAD

**Issue by panoply** [datocms/product-roadmap#173]
**Describe the bug**
When trying to define a default color value to an existing and/or newly created color field will results in a white page upon clicking.

**To Reproduce**
![example-dato-err](https://user-images.githubusercontent.com/7041324/61560190-e1eae100-aa6b-11e9-865e-3b051fe0f210.gif)

**Expected behavior**
Self explanatory 

**Additional context**

Console log spits out the following:

```
bundle.js:98 TypeError: o.filter is not a function
t.<computed> @ bundle.js:98
da @ bundle.js:173
n.callback @ bundle.js:173
oa @ bundle.js:173
ra @ bundle.js:173
Wa @ bundle.js:173
Va @ bundle.js:173
(anonymous) @ bundle.js:173
t.unstable_runWithPriority @ bundle.js:182
Is @ bundle.js:173
Ps @ bundle.js:173
Ts @ bundle.js:173
Rs @ bundle.js:173
jn @ bundle.js:173
e._rollbar_wrapped.e._rollbar_wrapped @ bundle.js:98
21:20:23.854 bundle.js:56 Uncaught TypeError: o.filter is not a function
```

**Comment by matjack1** [comment]
hello @panoply sorry but I cannot reproduce :(

If you can still reproduce, could you please share your project URL to us over support@datocms.com so that we can have a look at your specific case? Thank you!
