### ISSUE TITLE
Content Management API: Record data incomplete?

### ISSUE THREAD

**Issue by james-relyea** [datocms/product-roadmap#187]
**Describe the bug**
When using the Content Management API to pull down items from `/items`, all of our image fields are returning a string instead of an asset object.

Example: `thumbnailSmallUrl: '859676'`

Without making a list of all the different image field names, we don't have a great way of knowing when the field is actually string or an asset ID. We're then having to make subsequent requests to the `/uploads/:upload_id` endpoint to retrieve the image URL from the attributes.

**Expected behavior**
We expected to see the same properties structure that we see in the Webhook payloads:

```json
"thumbnail_small_url": {
  "path": "/path/to/image.jpg",
  "format": "jpeg",
  "size": 123,
  "alt": null,
  "title": null,
  "width": 123,
  "height": 123
}
```

**Comment by matjack1** [comment]
@james-relyea this is the intended behaviour, we return an upload ID that you can later use to retrieve the objects via the `/uploads` endpoint as you are saying.

If you want to get everything in one go you should consider using the GraphQL API? Not sure if it would be a viable option for you though.
