### ISSUE TITLE
Advanced search, filters and facets in the front end

### ISSUE THREAD

**Issue by stefanoverna** [datocms/product-roadmap#28]
A better search tool! 
 

-----

Originally posted by developerspp@gmail.com

**Comment by stefanoverna** [comment]
I'd like to see an automated linking to Algolia, which would send and resend structured data on changes the way Dato currently pings the build service. 
 

-----

Originally posted by lunelson@gmail.com

**Comment by stefanoverna** [comment]
Shipped! https://www.datocms.com/changelog/new-tabular-visualization-mode/

**Comment by andresgutgon** [comment]
One thing we are missing in search is ability for searching in all the languages. Now if you search for `slug` field in your model it will only find the slugs in your first language.
