### ISSUE TITLE
Radio/select options with predefined values

### ISSUE THREAD

**Issue by stefanoverna** [datocms/product-roadmap#41]
You currently cannot create fields which shows a predefined list of options to choose from.

**Comment by Convincible** [comment]
Can't you? I am sure I have done this with a Text Field with Validation of "Accept only specified values"

**Comment by shansmith01** [comment]
@Convincible is right (thanks for pointing it out).

eg here

<img width="556" alt="screen shot 2018-07-26 at 5 59 47 pm" src="https://user-images.githubusercontent.com/1866452/43293034-cadac224-90fd-11e8-96bc-72afe1fd2bd4.png">

**Comment by stefanoverna** [comment]
Shipped as a plugin! https://www.datocms.com/plugins/i/@ecologicdatocms-plugin-multiselect/
