### ISSUE TITLE
Document how to obtain localisable image infos

### ISSUE THREAD

**Issue by patricknick** [datocms/product-roadmap#48]
When using images in a mulit-language website, it would be good to have the title and alt tag of each image localised as well. Currently there is only one language per image / asset available.

**Comment by inekeg** [comment]
Same here, a feature that would really help us out.

**Comment by matjack1** [comment]
Hello, we have added some documentation to our localization page: https://www.datocms.com/docs/introduction/localization/#how-to-localize-images-title-and-alt

Any feedback is greatly appreciated!

**Comment by Convincible** [comment]
Thanks @matjack1, it's a good compromise and clever solution for the time being!

**Comment by patricknick** [comment]
@matjack1 If I'm not wrong, it's not possible to nest modular fields, right? Therefore this solution is not really useful. We ended up setting up a similar model and used a multiple-link field. It's working, but for the user, this is very hard to understand and maintain.

**Comment by tai-flywire** [comment]
It's a passable stop-gap solution but I agree with @patricknick.  Not only is it less usable for content editors but it requires a lot of work to retrofit the Dato project and then also to update the code to handle the new modular field.  I mean, how many thousands of images does the typical website have?  And we're supposed to update them all?  This needs to be an update to the native image object.  I'd really appreciate a new ticket for a long-term solution.

**Comment by matjack1** [comment]
Thank you @patricknick and @tai-flywire for the feedback.
I appreciate your comments and we'll take them for our future developments. We are in a phase in which we need to stabilise a few things to have better foundations to grow and release more features. We'll surely improve on this one though. It's just a matter of when!

We'll consider how to better implement this and open a new ticket for a long-term solution soon.

**Comment by patricknick** [comment]
@matjack1 thanks for the info. Stabilising sound very good, no feature can compensate this. 😊

**Comment by matjack1** [comment]
Hello @patricknick @Convincible @tai-flywire @inekeg 

I'm briefly commenting this old issue only to let you know that we have properly addressed this localisation issue now.

You can read more here: https://www.datocms.com/docs/general-concepts/media-area#localisation

And if you have any issue please come over at https://community.datocms.com/ as this Github repo is now archived and discontinued.
