### ISSUE TITLE
Linked singleton model for multiple-record models (e.g. products_index ↔ products)

### ISSUE THREAD

**Issue by Convincible** [datocms/product-roadmap#57]
For example, I have a model:

`products`: multiple
* `title`: single-text
* `image`: image
* `description`: multi-text

I am now able to edit any number of `product` items. However, where can I capture content/data about all products overall? e.g.:

* `products_heading`: single-text (localised)
* `todays_discount`: numeric
* `products_per_page`: numeric

Feature request: when selecting the model in the navigation menu, before selecting an individual item, you are editing the linked singleton model (if defined).

Essentially this is just a feature for how the admin interface menu appears. It can be up to the developer to "actually" code the link between the singleton and the multi model.

**Comment by stefanoverna** [comment]
I'm going to close this, not really sure if this is the right approach to the problem.
