### ISSUE TITLE
Define mixed-model trees for navigation menu

### ISSUE THREAD

**Issue by Convincible** [datocms/product-roadmap#58]
Ability to specify that the nav menu should interleave 2+ different models to form a navigable tree for the end user. For instance:

* `categories`
   * `products`

This could use the same interface at present for specifying the navigation menu and assigning models. However, when nesting a model underneath another one, if the nested model contains a link field which can pick from the container model, an option to interleave the items is exposed.

* `categories`
   * `products`: contains field: `category`: link (`categories`) → [✓] mixed model tree?

UX result:

* Clothes (`category`)
   * Tops (`product`)
   * Trousers (`product`)
   * Hats (`product`)
* Flowers (`category`)
   * Tulips (`product`)
   * Roses (`product`)
* No Category (for nested model items where link not yet given)
   * Radios (`product`)
   * Boats (`product`)

**Comment by stefanoverna** [comment]
This is extremely complex to accomplish, and very few people so far have requested it. So we won't work on this one in the foreseeable future, sorry guys :(

**Comment by Convincible** [comment]
I wonder if few people have requested just because it's not obvious this would be the issue to solve the problem — the use case to me seems obvious, such as Category/Product structures.

Recognise it's a complex one though!
