### ISSUE TITLE
Show usages of model instances

### ISSUE THREAD

**Issue by tai-flywire** [datocms/product-roadmap#73]
If you find a problem with or need to make a change to a certain model instance, it can be hard to find out where that instance is being used.  It would be _extremely_ useful to display the usages of any given instance.

![image](https://user-images.githubusercontent.com/39804991/43974761-8195f752-9ca9-11e8-9593-37222e831ea0.png)

**Comment by stefanoverna** [comment]
We have this as a plugin now: https://www.datocms.com/plugins/i/datocms-plugin-inverse-relationships/
