### ISSUE TITLE
Copy modular blocks from one language to others

### ISSUE THREAD

**Issue by lapidus** [datocms/product-roadmap#75]
Currently, it is quite painstaking to create the same list of modular blocks for each language. After creating 5 blocks of content (Paragraph, Image, Video etc.) in one Language and then moving to the next one, the process has to be restarted from scratch. 

I think the preferred default scenario for most editors would instead be to have the same modular structure for each language and only fill out the translations.

Would it be possible with some sort of switch that allows using one language's Modular structure as the master for all for that specific field? See the Red text in this image:

![image](https://user-images.githubusercontent.com/66601/44026947-e7de4ae2-9f1e-11e8-9bd7-6970e44b3d3d.png)

**Comment by dbismut** [comment]
Upping this, but ideally you would be able to select in settings which fields of the modular block require localization as you would for any other fields. That way, the modular content parent block itself would not have a localization option, only its children blocks would.

![dato](https://user-images.githubusercontent.com/5003380/46601930-02eed080-caef-11e8-9661-b98b3c41128d.jpg)

**Comment by panoply** [comment]
Making some noise on this one, really hard when working with multiple languages.

**Comment by souljuse** [comment]
Done! https://staging--datocms.netlify.com/changelog/copy-modular-content-structure-from-another-language
