### ISSUE TITLE
Ability to select existing records in embedded form

### ISSUE THREAD

**Issue by bauhem** [datocms/product-roadmap#88]
Need the Ability to select existing records in embedded form. Thanks

**Comment by tai-flywire** [comment]
+1

I came here to submit this exact feature request.  If the embedded form has this feature, then there is no need to even maintain the "select input" form.  Less code, less bugs, better UI.

One more minor request on the embedded form, though.  The height of the linked records could be a little more compact without sacrificing any readability.

**Comment by helloflow** [comment]
This would be a much appreciated feature. Any news on this?

**Comment by manchoz** [comment]
+1

**Comment by andresgutgon** [comment]
Yes please +1 

Love this idea ❤️:
> If the embedded form has this feature, then there is no need to even maintain the "select input" form

Without this is hard for us to switch to embedded forms. The product itself is less usable imo

**Comment by stefanoverna** [comment]
Done! 🍸

![2019-03-11 11 28 26](https://user-images.githubusercontent.com/51573/54117883-15e53400-43f2-11e9-853f-a11b69385e50.gif)

**Comment by andresgutgon** [comment]
Awesome! 👏
